require: rubocop-rspec

HashSyntax:
  EnforcedStyle: hash_rockets

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 15

Style/ModuleFunction:
  Enabled: false

AlignHash:
  EnforcedHashRocketStyle: table
