require: rubocop-rspec

AllCops:
  NewCops: enable

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 15

Style/ModuleFunction:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Style/OptionalBooleanParameter:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2
