name: Ruby Gem

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: bundle install
    - name: Publish to RubyGems
      run: |
        rake release
      env:
        GEM_HOST_API_KEY: "${{secrets.GEM_HOST_API_KEY}}"
